# Generated by Django 4.0.2 on 2022-03-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='voter',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
